services:
  ##################
  #    Westonia    #
  # Velocity Proxy #
  ##################
  westonia-proxy:
    image: itzg/mc-proxy
    environment:
      tty: "TRUE"
      stdin_open: "TRUE"
      # Proxy settings      
      TYPE: "VELOCITY"
      VELOCITY_BUILD_ID: "${VELOCITY_BUILD-latest}"
      MEMORY: ${PROXY_MEMORY-512M}
      ICON: "${ICON}"
      # Enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_SUFFIXES: "yml,yaml,txt,cfg,conf,properties,hjson,json,tml,toml,secret"
      ENV_VARIABLE_PREFIX: "WST_"
      # Set variables
      WST_ENVIRONMENT: "${ENVIRONMENT}" # Used for servers configuration (see Docker/MineraftDefaults/ConfigProxy/velocity.toml in [servers])
      WST_VELOCITY_SECRET: "${NETWORK_SECRET}"
      WST_PROXY_MOTD: "${MOTD}"
      WST_PROXY_MAX_PLAYERS: "${PROXY_MAX_PLAYERS-25}"
    ports:
      - "${HOST_PORT-25565}:25565"
    restart: always
    volumes:
      # Proxy data
      - ./Docker/ServiceData/${ENVIRONMENT}/westonia-proxy-data:/server
      # Proxy config
      - ./Docker/MinecraftDefaults/ConfigProxy/velocity.toml:/config/velocity.toml
      - ./Docker/MinecraftDefaults/ConfigProxy/forwarding.secret:/config/forwarding.secret
      # Proxy plugins
      #- ./Docker/MinecraftDefaults/PluginsProxy:/plugins
    networks:
      - minecraft

  ################
  #   Westonia   #
  # Lobby Server #
  ################
  westonia-lobby:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: "${LOBBY_MEMORY-2G}"
      TYPE: "PURPUR"
      tty: "TRUE"
      stdin_open: "TRUE"
      ONLINE_MODE: "FALSE"
      PURPUR_BUILD: "${PURPUR_BUILD-latest}"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      MAX_PLAYERS: "${LOBBY_MAX_PLAYERS-15}"
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      REPLACE_ENV_SUFFIXES: "yml,yaml,txt,cfg,conf,properties,hjson,json,tml,toml,secret"
      ENV_VARIABLE_PREFIX: "WST_"
      # Set variables
      WST_VELOCITY_SECRET: "${NETWORK_SECRET}"
    restart: always
    volumes:
      # Lobby data
      - ./Docker/ServiceData/${ENVIRONMENT}/westonia-lobby-data:/data
      # Lobby config
      - ./Docker/MinecraftDefaults/GeneralPurpurConfig/config/paper-global.yml:/config/paper-global.yml
      #- ./Docker/MinecraftDefaults/ConfigLobby/config.yml:/config/PluginConfig/config.yml
      # Lobby plugins
      #- ./Docker/MinecraftDefaults/PluginsLobby:/plugins
    networks:
      - minecraft

  ###################
  #    Westonia     #
  # Roleplay Server #
  ###################
  westonia-rp:
    build:
      context: Docker/
      dockerfile: Dockerfiles/WestoniaRP.Dockerfile
    environment:
      EULA: "TRUE"
      MEMORY: "${RP_MEMORY-2G}"
      TYPE: "PURPUR"
      tty: "TRUE"
      stdin_open: "TRUE"
      ONLINE_MODE: "FALSE"
      PURPUR_BUILD: "${PURPUR_BUILD-latest}"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      MAX_PLAYERS: "${RP_MAX_PLAYERS-15}"
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      REPLACE_ENV_SUFFIXES: "yml,yaml,txt,cfg,conf,properties,hjson,json,tml,toml,secret"
      ENV_VARIABLE_PREFIX: "WST_"
      # Set variables
      WST_VELOCITY_SECRET: "${NETWORK_SECRET}"
    restart: always
    volumes:
      # RP data
      - ./Docker/ServiceData/${ENVIRONMENT}/westonia-rp-data:/data
      # RP config
      - ./Docker/MinecraftDefaults/GeneralPurpurConfig/config/paper-global.yml:/config/paper-global.yml
      #- ./Docker/MinecraftDefaults/ConfigRP/config.yml:/config/PluginConfig/config.yml
      # RP plugins
      #- ./Docker/MinecraftDefaults/PluginsRP:/plugins
    networks:
      - minecraft

  ###################
  #    Westonia     #
  # Building Server #
  ###################
  westonia-building:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: "${BUILDING_MEMORY-2G}"
      TYPE: "PURPUR"
      tty: "TRUE"
      stdin_open: "TRUE"
      ONLINE_MODE: "FALSE"
      PURPUR_BUILD: "${PURPUR_BUILD-latest}"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      MAX_PLAYERS: "${BUILDING_MAX_PLAYERS-15}"
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      REPLACE_ENV_SUFFIXES: "yml,yaml,txt,cfg,conf,properties,hjson,json,tml,toml,secret"
      ENV_VARIABLE_PREFIX: "WST_"
      # Set variables
      WST_VELOCITY_SECRET: "${NETWORK_SECRET}"
    restart: always
    volumes:
      # Building data
      - ./Docker/ServiceData/${ENVIRONMENT}/westonia-building-data/:/data
      # Building config
      - ./Docker/MinecraftDefaults/GeneralPurpurConfig/config/paper-global.yml:/config/paper-global.yml
      #- ./Docker/MinecraftDefaults/ConfigBuilding/config.yml:/config/PluginConfig/config.yml
      # Building plugins
      #- ./Docker/MinecraftDefaults/PluginsBuilding/:/plugins
    networks:
      - minecraft

############
# Networks #
############
networks:
  #############
  # Minecraft #
  #############
  minecraft:
    driver: bridge

###########
# Volumes #
###########
#volumes:
#  westonia-proxy-data:
#  westonia-lobby-data:
#  westonia-rp-data:
